{{- if index .Values "kubeclarity-postgresql" "enabled" }}
{{- if index .Values "kubeclarity-postgresql-external" "enabled" }}
{{- fail "kubeclarity-postgresql and kubeclarity-postgresql-external can not both be enabled!" }}
{{- end }}
{{- end }}
{{- $secretKey := index .Values "kubeclarity-postgresql-secret" "secretKey" -}}
{{- $usernameKey := index .Values "kubeclarity-postgresql-secret" "usernameKey" -}}
{{- $hostKey := index .Values "kubeclarity-postgresql-secret" "hostKey" -}}
{{- $portKey := index .Values "kubeclarity-postgresql-secret" "portKey" -}}
{{- $databaseKey := index .Values "kubeclarity-postgresql-secret" "databaseKey" -}}
{{- $sslmodeKey := index .Values "kubeclarity-postgresql-secret" "sslmodeKey" -}}
{{- $secretName := index .Values "kubeclarity-postgresql" "auth" "existingSecret" -}}
{{ if index .Values "kubeclarity-postgresql-external" "enabled" }}
  {{- $secretName = index .Values "kubeclarity-postgresql-external" "auth" "existingSecret" -}}
{{ end }}
{{- $affinity := (coalesce .Values.kubeclarity.affinity .Values.global.affinity) -}}
{{- $tolerations := (coalesce .Values.kubeclarity.tolerations .Values.global.tolerations) -}}
{{- $nodeSelector := (coalesce .Values.kubeclarity.nodeSelector .Values.global.nodeSelector) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeclarity.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "kubeclarity.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kubeclarity.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeclarity.name" . }}
      {{- with  .Values.kubeclarity.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kubeclarity.name" . }}
      {{- if $affinity }}
      affinity: {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if $tolerations }}
      tolerations: {{- toYaml $tolerations | nindent 8 }}
      {{- end }}
      {{- if $nodeSelector }}
      nodeSelector: {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      initContainers:
        - name: '{{ include "kubeclarity.name" . }}-wait-for-pg-db'
          image: {{ index .Values "kubeclarity-postgresql" "image" "registry" }}/{{ index .Values "kubeclarity-postgresql" "image" "repository" }}:{{ index .Values "kubeclarity-postgresql" "image" "tag" }}
          command: ['sh', '-c', 'until pg_isready -h "$DB_HOST" -p "$DB_PORT_NUMBER" -U "$DB_USER" -d "dbname=$DB_NAME";
            do echo waiting for database; sleep 2; done;']
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $databaseKey }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $hostKey }}
            - name: DB_PORT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $portKey }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $usernameKey }}
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          {{- if not .Values.global.openShiftRestricted }}
            runAsUser: 1001
          {{- end }}
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml .Values.kubeclarity.initContainers.resources | nindent 12 }}
        - name: '{{ include "kubeclarity.name" . }}-wait-for-sbom-db'
          image: {{ index .Values "curl" "image" "registry" }}/{{ index .Values "curl" "image" "repository" }}:{{ index .Values "curl" "image" "tag" }}
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://{{ include "kubeclarity.sbom-db.name" . }}:8081/healthz/ready" -o /dev/null) -ne 200 ]; do
                echo waiting for sbom database; sleep 2;
              done;
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          {{- if not .Values.global.openShiftRestricted }}
            runAsUser: 1001
          {{- end }}
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml .Values.kubeclarity.initContainers.resources | nindent 12 }}
{{- if index .Values "kubeclarity-grype-server" "enabled" }}
        - name: '{{ include "kubeclarity.name" . }}-wait-for-grype-server'
          image: {{ index .Values "curl" "image" "registry" }}/{{ index .Values "curl" "image" "repository" }}:{{ index .Values "curl" "image" "tag" }}
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://{{ include "kubeclarity.grype-server.name" . }}:8080/healthz/ready" -o /dev/null) -ne 200 ]; do
                echo waiting for grype-server to be ready; sleep 2;
              done;
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          {{- if not .Values.global.openShiftRestricted }}
            runAsUser: 1001
          {{- end }}
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml .Values.kubeclarity.initContainers.resources | nindent 12 }}
{{- end}}
      containers:
        - name: kubeclarity
          {{- if .Values.kubeclarity.docker.imageName }}
          image: '{{ .Values.kubeclarity.docker.imageName }}'
          {{- else }}
          image: '{{ .Values.global.docker.registry }}/kubeclarity:{{ .Values.global.docker.tag }}'
          {{- end }}
          imagePullPolicy: {{ .Values.global.docker.imagePullPolicy }}
          args:
            - run
            - --log-level
            - {{ .Values.kubeclarity.logLevel }}
          env:
            - name: ENABLE_DB_INFO_LOGS
              value: "{{ .Values.kubeclarity.enableDBInfoLog }}"
{{- if index .Values.kubeclarity.prometheus.enabled }}
            - name: PROMETHEUS_REFRESH_INTERVAL_SECONDS
              value: "{{ .Values.kubeclarity.prometheus.refreshIntervalSeconds }}"
{{- end }}
            # DB envs
            {{- if .Values.kubeclarity.dbViewRefreshInterval }}
            - name: DB_VIEW_REFRESH_INTERVAL
              value: "{{ .Values.kubeclarity.dbViewRefreshInterval }}"
            {{- end }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $databaseKey }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $hostKey }}
            - name: DB_PORT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $portKey }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $usernameKey }}
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $sslmodeKey }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $secretKey }}
            # runtime-scan envs
            - name: SCANNER_JOB_RESULT_LISTEN_PORT
              value: "{{ index .Values "kubeclarity-runtime-scan" "resultServicePort" }}"
            - name: SCANNER_JOB_TEMPLATE_CONFIG_MAP_NAME
              value: "{{ include "kubeclarity.name" . }}-scanner-template"
            - name: SCANNER_JOB_TEMPLATE_CONFIG_MAP_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: CREDS_SECRET_NAMESPACE
              value: "{{ .Release.Namespace }}"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8888
              name: scan-results
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8081
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            {{- if not .Values.global.openShiftRestricted }}
            runAsGroup: 1000
            runAsUser: 1000
            {{- end }}
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
{{- toYaml .Values.kubeclarity.resources | nindent 12 }}
