{{- $secretName := index .Values "kubeclarity-postgresql" "auth" "existingSecret" -}}
{{- $postgresPassword := .Values.global.databasePassword | b64enc -}}
{{- $dbHost := print (include "kubeclarity.name" .) "-postgresql" | b64enc -}}
{{- $dbPort := index .Values "kubeclarity-postgresql" "service" "ports" "postgresql" | toString | b64enc -}}
{{- $dbUser := index .Values "kubeclarity-postgresql" "auth" "username" | b64enc -}}
{{- $dbName := index .Values "kubeclarity-postgresql" "auth" "database" | b64enc -}}
{{- $dbSSLMode := index .Values "kubeclarity-postgresql" "auth" "sslMode" | b64enc -}}
{{- if index .Values "kubeclarity-postgresql-external" "enabled" }}
  {{- $secretName = index .Values "kubeclarity-postgresql-external" "auth" "existingSecret" -}}
  {{- $dbHost = index .Values "kubeclarity-postgresql-external" "auth" "host" | b64enc -}}
  {{- $dbPort = index .Values "kubeclarity-postgresql-external" "auth" "port" | toString | b64enc -}}
  {{- $dbUser = index .Values "kubeclarity-postgresql-external" "auth" "username" | b64enc -}}
  {{- $dbName = index .Values "kubeclarity-postgresql-external" "auth" "database" | b64enc -}}
  {{- $dbSSLMode = index .Values "kubeclarity-postgresql-external" "auth" "sslMode" | b64enc -}}
{{- end }}
{{- $secretKey := index .Values "kubeclarity-postgresql-secret" "secretKey" -}}
{{- $usernameKey := index .Values "kubeclarity-postgresql-secret" "usernameKey" -}}
{{- $hostKey := index .Values "kubeclarity-postgresql-secret" "hostKey" -}}
{{- $portKey := index .Values "kubeclarity-postgresql-secret" "portKey" -}}
{{- $databaseKey := index .Values "kubeclarity-postgresql-secret" "databaseKey" -}}
{{- $sslmodeKey := index .Values "kubeclarity-postgresql-secret" "sslmodeKey" -}}

{{- if (index .Values "kubeclarity-postgresql-secret" "create") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "kubeclarity.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
data:
  {{ $secretKey }}: {{ $postgresPassword }}
  {{ $usernameKey }}: {{ $dbUser }}
  {{ $hostKey }}: {{ $dbHost }}
  {{ $portKey }}: {{ $dbPort }}
  {{ $databaseKey }}: {{ $dbName }}
  {{ $sslmodeKey }}: {{ $dbSSLMode }}
{{- end }}
