apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeclarity.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "kubeclarity.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
{{ template "kubeclarity.service.annotations" .}}
spec:
  type: {{ .Values.kubeclarity.service.type }}
  ports:
    - name: backend
      port: {{ .Values.kubeclarity.service.port }}
      protocol: TCP
      targetPort: 8080
    - name: runtime-scan-results
      port: {{ index .Values "kubeclarity-runtime-scan" "resultServicePort" }}
      protocol: TCP
      targetPort: {{ index .Values "kubeclarity-runtime-scan" "resultServicePort" }}
    {{- if .Values.kubeclarity.prometheus.enabled }}
    - name: metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
    {{- end }}
  selector:
    app: {{ include "kubeclarity.name" . }}
