name: 'Build and Push Component'

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: 'Name of the image to publish'
      image_tag:
        required: true
        type: string
        description: 'Image tag to build and push.'
      push:
        required: false
        type: boolean
        description: 'If set to true, push the image.'
        default: false
      timestamp:
        required: true
        type: string
        description: 'The build timestamp to be used for binaries.'
      bake_target_name:
        required: true
        type: string
        description: 'Docker Bake target name.'
      post_image_tags:
        required: false
        type: boolean
        description: |
          If set to true the image tags pushed to the repository are posted as comment for the Pull Request.
          Only works if the event type is `pull_request`.

jobs:
  build-vars:
    runs-on: ubuntu-latest
    outputs:
      digests-cache-name: ${{ steps.build-vars.outputs.digests-cache-name }}
    steps:
      - name: Set build variables
        id: build-vars
        run: |

          ##
          ## Set digests cache name
          ##
          ##    Example: digest-1234-a2850e9cc4e2b3a3
          ##

          image_name_hash="$(sha256sum <<< "${{ inputs.bake_target_name }}" | cut -f1 -d' ')"
          printf "digests-cache-name=digest-%s-%.16s" "${{ github.run_id }}" "${image_name_hash}" >> "$GITHUB_OUTPUT"

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-vars
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Cache Docker layers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@7a5dfed3550ca014665af2a27af8fc9d7284b9b3 # v4.5.0
        id: bake
        with:
          targets: ${{ inputs.bake_target_name }}
          set: |
            *.platform=${{ matrix.platform }}
            *.output=type=image,name=${{ inputs.image_name }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
            *.tags=
            *.cache-to=type=local,dest=/tmp/.buildx-cache
            *.cache-from=type=local,src=/tmp/.buildx-cache
        env:
          VERSION: ${{ inputs.image_tag }}
          BUILD_TIMESTAMP: ${{ inputs.timestamp }}
          COMMIT_HASH: ${{ github.sha }}
          BUILD_OPTS: -tags=exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper

      - name: Export digest
        if: inputs.push
        id: digest
        run: |
          mkdir -p /tmp/digests
          digest=$(jq -r '."${{ inputs.bake_target_name }}"."containerimage.digest"'<<< '${{ steps.bake.outputs.metadata }}')
          touch "/tmp/digests/${digest#sha256:}"
          echo "digest=${digest#sha256:}" >> "$GITHUB_OUTPUT"

      - name: Upload digests
        if: inputs.push
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ needs.build-vars.outputs.digests-cache-name }}-${{ steps.digest.outputs.digest }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  merge-and-push:
    if: inputs.push
    runs-on: ubuntu-latest
    needs:
      - build-vars
      - build-and-push
    steps:
      - name: Download digests
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          pattern: ${{ needs.build-vars.outputs.digests-cache-name }}-*
          merge-multiple: true
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          # shellcheck disable=SC2046
          docker buildx imagetools create \
            --tag "${{ inputs.image_name }}:${{ inputs.image_tag }}" \
            $(printf '${{ inputs.image_name }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ inputs.image_name }}:${{ inputs.image_tag }}

      - name: Save image name
        if: inputs.post_image_tags
        run: |
          mkdir -p /tmp/image-names
          echo "${{ inputs.image_name }}:${{ inputs.image_tag }}" >> "/tmp/image-names/${{ inputs.bake_target_name }}"

      - name: Upload image names
        if: inputs.post_image_tags
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: image-names-${{ github.run_id }}-${{ inputs.bake_target_name }}
          path: /tmp/image-names/*
          if-no-files-found: error
