name: 'Build and Push Component'

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
        description: 'Dockerfile to build and push'
      image_name:
        required: true
        type: string
        description: 'Name of the image to publish'
      image_tag:
        required: true
        type: string
        description: 'Image tag to build and push.'
      push:
        required: false
        type: boolean
        description: 'If set to true, push the image.'
        default: false
      timestamp:
        required: true
        type: string
        description: 'The build timestamp to be used for binaries.'

jobs:
  build-vars:
    runs-on: ubuntu-latest
    outputs:
      digests-cache-name: ${{ steps.build-vars.outputs.digests-cache-name }}
    steps:
      - name: Set build variables
        id: build-vars
        run: |
          
          ##
          ## Extract the image name
          ##
          ##    $ basename ghcr.io/openclarity/vmclarity-ui-dev
          ##    vmclarity-ui-dev
          ##
          image_name="$(basename ${{ inputs.image_name }})"
          
          ##
          ## Set digests cache name
          ##
          ##    Example: digest-1234-a2850e9cc4e2b3a3
          ##
          
          image_name_hash="$(sha256sum <<< "${image_name}" | cut -f1 -d' ')"
          printf "digests-cache-name=digest-%s-%.16s" "${{ github.run_id }}" "${image_name_hash}" >> "$GITHUB_OUTPUT"

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-vars
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Cache Docker layers
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        id: build
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ${{ inputs.dockerfile }}
          outputs: type=image,name=${{ inputs.image_name }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ inputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Export digest
        if: inputs.push
        id: digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          
          echo "digest=${digest#sha256:}" >> "$GITHUB_OUTPUT"

      - name: Upload digests
        if: inputs.push
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: ${{ needs.build-vars.outputs.digests-cache-name }}-${{ steps.digest.outputs.digest }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  merge-and-push:
    if: inputs.push
    runs-on: ubuntu-latest
    needs:
      - build-vars
      - build-and-push
    steps:
      - name: Download digests
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          pattern: ${{ needs.build-vars.outputs.digests-cache-name }}-*
          merge-multiple: true
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          # shellcheck disable=SC2046
          docker buildx imagetools create \
            --tag "${{ inputs.image_name }}:${{ inputs.image_tag }}" \
            $(printf '${{ inputs.image_name }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ inputs.image_name }}:${{ inputs.image_tag }} 
