name: Build & Push

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: 'Image tag to build and push.'
      push:
        required: false
        type: string
        description: 'If set to true, push the image.'
        default: false
      upload:
        required: false
        type: string
        description: 'If set to true, upload the image.'
        default: false

jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

  kubeclarity:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/openclarity/kubeclarity:${{ inputs.image_tag }}
          file: Dockerfile.backend
          push: ${{ inputs.push }}
          outputs: type=docker,dest=/tmp/kubeclarity.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubeclarity
          path: /tmp/kubeclarity.tar

  cis_docker_benchmark_scanner:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/openclarity/kubeclarity-cis-docker-benchmark-scanner:${{ inputs.image_tag }}
          file: Dockerfile.cis_docker_benchmark_scanner
          push: ${{ inputs.push }}
          outputs: type=docker,dest=/tmp/cis_docker_benchmark_scanner.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cis_docker_benchmark_scanner
          path: /tmp/cis_docker_benchmark_scanner.tar

  runtime_k8s_scanner:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/openclarity/kubeclarity-runtime-k8s-scanner:${{ inputs.image_tag }}
          file: Dockerfile.runtime_k8s_scanner
          push: ${{ inputs.push }}
          outputs: type=docker,dest=/tmp/runtime_k8s_scanner.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: runtime_k8s_scanner
          path: /tmp/runtime_k8s_scanner.tar

  sbom_db:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/openclarity/kubeclarity-sbom-db:${{ inputs.image_tag }}
          file: Dockerfile.sbom_db
          push: ${{ inputs.push }}
          outputs: type=docker,dest=/tmp/kubeclarity-sbom-db.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubeclarity-sbom-db
          path: /tmp/kubeclarity-sbom-db.tar

  cli:
    needs: timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/openclarity/kubeclarity-cli:${{ inputs.image_tag }}
          file: Dockerfile.cli
          push: ${{ inputs.push }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ inputs.image_tag }}
            BUILD_TIMESTAMP=${{ needs.timestamp.outputs.timestamp }}
            COMMIT_HASH=${{ github.sha }}